image: "python:3.7.7-buster"
stages:
  - test
  - train
  - deploy

dvc:
  stage: train
  script:
    - pip install dvc==1.0.2
    - pip install -r requirements.txt
    - python nltk_install.py
    - dvc repro
  artifacts:
    paths:
      - mwsa/output/models/de.pkl
      - mwsa/output/models/en.pkl
    expire_in: 4 weeks

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python nltk_install.py
    - pytest -o log_cli=true  test/


deploy:
  image: google/cloud-sdk
  stage: deploy
  script:
    - echo $GOOGLE_SERVICE_ACCOUNT_FILE > /tmp/$CI_PIPELINE_ID.json
    - gcloud init
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gsutil cp mwsa/output/models/* gs://elexis_mwsa_models


#staging:
#  stage: deploy
#  script:
#    - apt-get update -qy
#    - apt-get install -y ruby-dev
#    - gem install dpl
#    - dpl --provider=heroku --app=gitlab-ci-python-test-staging --api-key=$HEROKU_STAGING_API_KEY
#  only:
#    - master
