stages:
  en:
    cmd: python -m mwsa_model.load_data data/train english_kd.tsv
    deps:
    - data/train/english_kd.tsv
    - mwsa_model/load_data.py
    outs:
    - mwsa_model/data/features_english_kd.tsv.pkl
    - mwsa_model/data/labels_english_kd.tsv.pkl
  en_train:
    cmd: python -m mwsa_model.preprocess features_english_kd.tsv.pkl labels_english_kd.tsv.pkl en
    deps:
    - mwsa_model/data/features_english_kd.tsv.pkl
    - mwsa_model/data/labels_english_kd.tsv.pkl
    - mwsa_model/preprocess.py
    - mwsa_model/service/model_trainer.py
    metrics:
    - mwsa_model/output/metrics/en_cv_score.txt:
        cache: false
    outs:
    - mwsa_model/output/models/en.pkl
    - mwsa_model/output/models/en.joblib
  en_evaluate:
    cmd: python -m mwsa_model.evaluate en.pkl english_nuig.tsv metrics_en.txt en_predictions.txt
    deps:
    - data/reference_data/english_nuig.tsv
    - data/test/english_nuig.tsv
    - mwsa_model/evaluate.py
    - mwsa_model/output/models/en.pkl
    metrics:
    - mwsa_model/output/metrics/metrics_en.txt:
        cache: false
    outs:
    - mwsa_model/output/predictions/en_predictions.txt
  de:
    cmd: python -m mwsa_model.load_data data/train/ german.tsv
    deps:
    - data/train/german.tsv
    - mwsa_model/load_data.py
    outs:
    - mwsa_model/data/features_german.tsv.pkl
    - mwsa_model/data/labels_german.tsv.pkl
  de_train:
    cmd: python -m mwsa_model.preprocess features_german.tsv.pkl labels_german.tsv.pkl de
    deps:
    - mwsa_model/data/features_german.tsv.pkl
    - mwsa_model/data/labels_german.tsv.pkl
    - mwsa_model/preprocess.py
    - mwsa_model/service/model_trainer.py
    outs:
    - mwsa_model/output/models/de.pkl
    metrics:
    - mwsa_model/output/metrics/de_cv_score.txt:
        cache: false
  de_evaluate:
    cmd: python -m mwsa_model.evaluate de.pkl german.tsv metrics_de.txt de_predictions.txt
    deps:
    - data/reference_data/german.tsv
    - data/test/german.tsv
    - mwsa_model/evaluate.py
    - mwsa_model/output/models/de.pkl
    outs:
    - mwsa_model/output/predictions/de_predictions.txt
    metrics:
    - mwsa_model/output/metrics/metrics_de.txt:
        cache: false
